### ISSUE TITLE
Cannot find module 'graphql-schema-org'

### ISSUE THREAD

**Issue by xmnlab** [cape-io/graphql-schema-org#5]
hey everyone! I am trying to use the library but it is raising an error for me:

```
[nodemon] restarting due to changes...
[nodemon] starting `node src/index.js`
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'graphql-schema-org'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/mnt/sda1/dev/quansight/jupyterlab-metadata-service/backend/jupyterlab_metadata_service_server/src/schemas/data_catalog.js:11:25)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
[nodemon] app crashed - waiting for file changes before starting...

```

data_catalog.js:11 is:

`const { DataCatalog } = require('graphql-schema-org');`
but graphql-schema-org is on my node_modules folder.

I am not a nodejs expert so probably I am missing something.

any idea?

**Comment by xmnlab** [comment]
I added `"babel-cli": "^6.26.0"`into package.json/devDependencies and it fixed the problem.
I added also `"babel-tape-runner": "^3.0.0"` needed by the tests.

I will keep this issue opened. I will open a PR to fix this issue.

**Comment by xmnlab** [comment]
now I can build the lib but I when I try to install that as dependence ... it seems it is not installed properly

**Comment by xmnlab** [comment]
it seems the problem is raised because there is no `lib` folder on the package and package.json:main points to lib/index.js

I added lib folder into the #7 but not sure if it is the best practice but at least I can now install from my repo and it is working.
